"""add token_version to users

Revision ID: 0b47a72a4b89
Revises: bc98b938cdd5
Create Date: 2026-04-18 19:21:58.480612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b47a72a4b89'
down_revision: Union[str, Sequence[str], None] = 'bc98b938cdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_media_person_id_persons'), 'media', type_='foreignkey')
    op.drop_constraint(op.f('fk_media_story_id_stories'), 'media', type_='foreignkey')
    op.create_foreign_key(op.f('fk_media_story_id_stories'), 'media', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_media_person_id_persons'), 'media', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_constraint(op.f('fk_media_person_id_persons'), 'media', type_='foreignkey')
    op.drop_constraint(op.f('fk_media_story_id_stories'), 'media', type_='foreignkey')
    op.create_foreign_key(op.f('fk_media_story_id_stories'), 'media', 'stories', ['story_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_media_person_id_persons'), 'media', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
