"""add soft delete to persons and stories

Revision ID: 113728a9ca98
Revises: 9c0d79a46570
Create Date: 2026-04-21 14:43:07.673303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113728a9ca98'
down_revision: Union[str, Sequence[str], None] = '9c0d79a46570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'deleted_at')
    op.drop_column('persons', 'deleted_at')
    # ### end Alembic commands ###
