"""add_places_table

Revision ID: 4406df5b773f
Revises: 58c9504a7c0a
Create Date: 2026-04-19 22:12:50.126875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4406df5b773f'
down_revision: Union[str, Sequence[str], None] = '58c9504a7c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geocoder', sa.String(length=50), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index(op.f('ix_places_display_name'), 'places', ['display_name'], unique=False)
    op.add_column('persons', sa.Column('birth_place_id', sa.Uuid(), nullable=True))
    op.add_column('persons', sa.Column('death_place_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_persons_birth_place_id'), 'persons', ['birth_place_id'], unique=False)
    op.create_index(op.f('ix_persons_death_place_id'), 'persons', ['death_place_id'], unique=False)
    op.create_foreign_key(op.f('fk_persons_birth_place_id_places'), 'persons', 'places', ['birth_place_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_persons_death_place_id_places'), 'persons', 'places', ['death_place_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_persons_death_place_id_places'), 'persons', type_='foreignkey')
    op.drop_constraint(op.f('fk_persons_birth_place_id_places'), 'persons', type_='foreignkey')
    op.drop_index(op.f('ix_persons_death_place_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_birth_place_id'), table_name='persons')
    op.drop_column('persons', 'death_place_id')
    op.drop_column('persons', 'birth_place_id')
    op.drop_index(op.f('ix_places_display_name'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
