"""add_flexible_date_fields

Revision ID: 58c9504a7c0a
Revises: 9a8d8e0e2d45
Create Date: 2026-04-19 18:40:42.121192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c9504a7c0a'
down_revision: Union[str, Sequence[str], None] = '9a8d8e0e2d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('birth_date_qualifier', sa.String(length=20), nullable=True))
    op.add_column('persons', sa.Column('birth_date_2', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('birth_date_original', sa.String(length=50), nullable=True))
    op.add_column('persons', sa.Column('death_date_qualifier', sa.String(length=20), nullable=True))
    op.add_column('persons', sa.Column('death_date_2', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('death_date_original', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'death_date_original')
    op.drop_column('persons', 'death_date_2')
    op.drop_column('persons', 'death_date_qualifier')
    op.drop_column('persons', 'birth_date_original')
    op.drop_column('persons', 'birth_date_2')
    op.drop_column('persons', 'birth_date_qualifier')
    # ### end Alembic commands ###
