"""add icon to trees

Revision ID: 770e69f89169
Revises: 0c7b2710106b
Create Date: 2026-04-25 01:08:39.341366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770e69f89169'
down_revision: Union[str, Sequence[str], None] = '0c7b2710106b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_deleted_at'), table_name='persons')
    op.drop_index(op.f('ix_stories_deleted_at'), table_name='stories')
    op.add_column('trees', sa.Column('icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'icon')
    op.create_index(op.f('ix_stories_deleted_at'), 'stories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_persons_deleted_at'), 'persons', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
