"""add_person_fields

Revision ID: 9a8d8e0e2d45
Revises: a572e28ccc03
Create Date: 2026-04-19 17:28:18.730392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8d8e0e2d45'
down_revision: Union[str, Sequence[str], None] = 'a572e28ccc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('maiden_name', sa.String(length=255), nullable=True))
    op.add_column('persons', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('persons', sa.Column('death_location', sa.String(length=255), nullable=True))
    op.add_column('persons', sa.Column('is_living', sa.Boolean(), nullable=True))
    op.add_column('persons', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('persons', sa.Column('nationalities', sa.JSON(), nullable=True))
    op.add_column('persons', sa.Column('education', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('profile_picture_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_persons_profile_picture_id'), 'persons', ['profile_picture_id'], unique=False)
    op.create_foreign_key('fk_persons_profile_picture_id_media', 'persons', 'media', ['profile_picture_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_persons_profile_picture_id_media', 'persons', type_='foreignkey')
    op.drop_index(op.f('ix_persons_profile_picture_id'), table_name='persons')
    op.drop_column('persons', 'profile_picture_id')
    op.drop_column('persons', 'education')
    op.drop_column('persons', 'nationalities')
    op.drop_column('persons', 'occupation')
    op.drop_column('persons', 'is_living')
    op.drop_column('persons', 'death_location')
    op.drop_column('persons', 'nickname')
    op.drop_column('persons', 'maiden_name')
    # ### end Alembic commands ###
