"""remove direction from relationships

Revision ID: a572e28ccc03
Revises: 0b47a72a4b89
Create Date: 2026-04-18 19:52:49.984253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a572e28ccc03'
down_revision: Union[str, Sequence[str], None] = '0b47a72a4b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
