"""initial schema

Revision ID: bc98b938cdd5
Revises: 
Create Date: 2026-04-18 15:05:17.670968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc98b938cdd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trees',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_trees_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trees'))
    )
    op.create_table('persons',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('birth_location', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_persons_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_tree_id'), 'persons', ['tree_id'], unique=False)
    op.create_table('stories',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('event_location', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_stories_author_id_users')),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_stories_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index(op.f('ix_stories_author_id'), 'stories', ['author_id'], unique=False)
    op.create_index(op.f('ix_stories_tree_id'), 'stories', ['tree_id'], unique=False)
    op.create_table('tags',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_tags_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('tree_id', 'name', name=op.f('uq_tags_tree_id'))
    )
    op.create_index(op.f('ix_tags_tree_id'), 'tags', ['tree_id'], unique=False)
    op.create_table('tree_members',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'admin')", name=op.f('ck_tree_members_valid_role')),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_tree_members_tree_id_trees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tree_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tree_members')),
    sa.UniqueConstraint('tree_id', 'user_id', name=op.f('uq_tree_members_tree_id'))
    )
    op.create_table('media',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("media_type IN ('photo', 'audio', 'video', 'document', 'other')", name=op.f('ck_media_valid_media_type')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_media_person_id_persons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_media_story_id_stories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_media_tree_id_trees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_media_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_person_id'), 'media', ['person_id'], unique=False)
    op.create_index(op.f('ix_media_story_id'), 'media', ['story_id'], unique=False)
    op.create_index(op.f('ix_media_tree_id'), 'media', ['tree_id'], unique=False)
    op.create_table('relationships',
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('person_a_id', sa.Uuid(), nullable=False),
    sa.Column('person_b_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("direction IN ('one_way', 'mutual')", name=op.f('ck_relationships_valid_direction')),
    sa.CheckConstraint('person_a_id != person_b_id', name=op.f('ck_relationships_different_persons')),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], name=op.f('fk_relationships_person_a_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], name=op.f('fk_relationships_person_b_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('fk_relationships_tree_id_trees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_person_a_id'), 'relationships', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_person_b_id'), 'relationships', ['person_b_id'], unique=False)
    op.create_index(op.f('ix_relationships_tree_id'), 'relationships', ['tree_id'], unique=False)
    op.create_table('story_persons',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_story_persons_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_persons_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_persons')),
    sa.UniqueConstraint('story_id', 'person_id', name=op.f('uq_story_persons_story_id'))
    )
    op.create_table('story_tags',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_tags_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_story_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_tags')),
    sa.UniqueConstraint('story_id', 'tag_id', name=op.f('uq_story_tags_story_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_tags')
    op.drop_table('story_persons')
    op.drop_index(op.f('ix_relationships_tree_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_media_tree_id'), table_name='media')
    op.drop_index(op.f('ix_media_story_id'), table_name='media')
    op.drop_index(op.f('ix_media_person_id'), table_name='media')
    op.drop_table('media')
    op.drop_table('tree_members')
    op.drop_index(op.f('ix_tags_tree_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_stories_tree_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_author_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_persons_tree_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('trees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
